# Generated by Django 2.1 on 2018-11-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_key', models.CharField(max_length=32, unique=True)),
                ('mobile_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_time', models.DateTimeField(verbose_name='message received')),
                ('message_text', models.CharField(max_length=50)),
                ('lat', models.IntegerField(blank=True, default=-1, null=True)),
                ('lng', models.IntegerField(blank=True, default=-1, null=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(verbose_name='message sended')),
                ('message_text', models.CharField(max_length=50)),
                ('lat', models.IntegerField(blank=True, default=-1, null=True)),
                ('lng', models.IntegerField(blank=True, default=-1, null=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
