# Generated by Django 2.1 on 2018-11-09 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181108_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemessage',
            name='reception_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servermessage',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
