# Generated by Django 2.1 on 2018-11-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181109_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
    ]
